
name : dmacro-examples
brand : dmacro-examples
description : docs and code related to quantitative macro models
url : http://ricardomayerb.github.io/dmacro-examples
email : ricardomayerb@gmail.com
author: Ricardo Mayer

baseurl : http://ricardomayerb.github.io/dmacro-examples

permalink : none

# The following is a list of files to exclude from inclusion in the
# generated gh-pages website.
exclude : [ README.md , version.txt ]


# Replace the number with the default number of blot posts you want on each
# page. A value of 0 will indicate that you don't want to paginate, and all
# blog posts will be on the index page.
paginate : 0


# To put a alert or notice on every page served, change the appropriate value
# below from false to the message you want displayed (alert : Alert message
# or notice : Notice message). Alerts tend to show in red or orange, while
# notices in blue or green. But that is dependent upon the bootstrap theme
# that you use.
#
# Here's an example configuration:
# alert : This is a sample alert message.
# notice : This is a sample notice message.
alert : false
notice : false


# The favicon image served up to web browsers. Enable the local if you want
# to serve up a file directly from the gh-pages-blog. The partial URL will be
# appended to the site configured url above (basically don't include the part
# that is included in the URL above). If you want to use a favicon that
# is hosted elsewhere, disable the local and enable the remote and include the
# full url (http://www.something.domain/directory/file.extention). For either
# the local or remote, you'll need to include the file type.
#
# Here's an example configuration:
# favicon :
#   enabled : true
#   local :
#     enabled : false
#     partial_url : false
#     type : false
#   remote :
#     enabled : true
#     full_url : http://www.gravatar.com/avatar/2f8947394b8acb62e1055f27.png
#     type : png
favicon :
  enabled : true
  local :
    enabled : true
    partial_url : /favicon.ico
    type : ico
  remote :
    enabled : false
    full_url : false
    type : false

markdown: redcarpet
pandoc:
  extensions: 
    - smart
    - mathjax


# The navbar settings determine what menus are displayed on the navbar at the
# top of the page. Any navbar menu can be enabled by setting the enabled
# configuration setting to true. All of the navbar menu items are also navlist
# items described above. They work just like the navlist settings, except
# the navbar items are in dropdown menus.
#
# Here is an example configuration:
# navbar :
#   archive :
#     enabled : false
#   categories :
#     enabled : false
#   tags :
#     enabled : false
#   github_projects :
#     enabled : false
#   social_links :
#     enabled : false
#   external_links :
#     enabled : false
navbar :
  archive :
    enabled : true
  categories :
    enabled : true
  tags :
    enabled : true
  github_projects :
    enabled : false
  social_links :
    enabled : false
  external_links :
    enabled : false



# These are the bootstrap settings. These bootstrap settings will control both
# the theme and responsive settings of this site.
#
# css - The name of the bootstrap css. Using one of the min css should be
# fine. This also controls the general theme of the website, so using a custom
# bootstrap css should work just fine. Also any of the bootswatch settings
# should work just fine, but you may need to tweak the css settings in the
# css/gh-pages-blog.css if things clash.
#
# responsive : enabled - To enable a responsive bootstrap, set this value to
# true.
#
# responsive : css - The name of the bootstrap responsive css file to use. It
# should be just fine to use the min file.
#
# responsive : js : enabled - This either enables or disables the responsive
# bootstrap css. If you're going to use responsive css, you also need to use
# a responsive bootstrap js.
#
# responsive : js : src - The javascript to use for the responsive
# bootstrap. If you're going to use responsive css, you also need to use
# a responsive bootstrap js.
#
# Here's an example configuration:
# bootstrap:
#   css : bootstrap.min.css
#   responsive :
#     enabled : true
#     css : bootstrap-responsive.min.css
#   js :
#     enabled : true
#     src : bootstrap.min.js
bootstrap:
  css : bootstrap.min.css
  responsive :
    enabled : true
    css : bootstrap-responsive.min.css
  js :
    enabled : true
    src : bootstrap.min.js


# These are the configuration settings for the jquery javascript. JQuery is
# needed for responsive bootstrap and for the filter.html file.
#
# jquery : enabled - This enables or disables jquery. Disabling will probably
# cause the site to behave in a way that is unexpected.
#
# jquery : src - The source code file of the jquery to use.
#
# Here's an example configuration:
# jquery:
#   enabled : true
#   src : jquery-1.9.1.min.js
jquery:
  enabled : true
  src : jquery-1.9.1.min.js


# Font Awesome includes many different fonts that are used throughout the
# site. Although not required, the Font Awesome fonts make the website look
# much better.
#
# font_awesome : enabled - Enables or disables the use of font awesome.
#
# font_awesome : css - The css file to use for font awesome. The min css
# should be sufficient.
#
# Here's an example configuration:
# font_awesome :
#   enabled : true
#   css : font-awesome.min.css
font_awesome :
  enabled : true
  css : font-awesome.min.css


# This section of the configuration determins how syntax highlighting is
# configured and the css file to be used.
#
# syntax_highlighting : enabled - Enables or disables the loading of the
# css to be used for syntax highlighting of code blocks.
#
# syntax_highlighting : css - The name of the css file to use for syntax
# highlighting.
#
# Here's an example configuration:
# syntax_highlighting :
#   enabled : true
#   css : syntax.css
syntax_highlighting :
  enabled : true
  css : syntax.css


# This section of the configuration determines how the rss 2.0 xml file is
# configured. The rss.xml is generated based upon the following settings,
# as well as those above and on the post yml front-matter.
#
# enabled - This either enables or disables the generation of the rss.xml
# file.
#
# managing_editor : enabled - Enables or disables the inclusion of the
# managingEditor node in the xml.
#
# managing_editor : managing_editor - The email address and name of the
# managing editor. The format is fairly specific in that the email
# address is listed followed by an actual name in parenthesis:
# thedereck@thedereck.com (Dereck Curry).
#
# webmaster : enabled - Enables or disables the inclusion of the
# webmater node in the xml.
#
# webmaster : webmater - The email address and name of the
# webmaster. The format is fairly specific in that the email address is
# listed followed by an actual name in parenthesis:
# thedereck@thedereck.com (Dereck Curry).
#
# ttl : enabled - Enables or disables the inclusion of a ttl setting.
#
# ttl : ttl - The numeric value of the ttl in minutes.
#
# image : enabled - Enables or disables the inclusion of an image to
# represent the site in the xml.
#
# image : image - The full url of the image to use. Must include the
# http:// or https://.
#
# Here's an example configuration:
# rss :
#   enabled : true
#   managing_editor :
#     enabled : true
#     managing_editor : thedereck@thedereck.com (Dereck Curry)
#   webmaster :
#     enabled : true
#     webmaster : thedereck@thedereck.com (Dereck Curry)
#   ttl :
#     enabled : true
#     ttl : 300
#   image :
#     enabled : true
#     image : http://www.gravatar.com/avatar/0f08df91055f27.png?s=200
rss :
  enabled : true
  managing_editor :
    enabled : false
    managing_editor : false
  webmaster :
    enabled : false
    webmaster : false
  ttl :
    enabled : true
    ttl : 300
  image :
    enabled : false
    image : false

