---
layout: page
author: ricardo mayer
---

# Introducing a basic ('toy') model #


In theory, changes in productivity can have counter-intuitive effects. For instance, as noted by xxx, yyy and more recently zzz and aaa, if productivity has a long term growth rate of 2\% and suddenly rises to a new long term growth rate of 4\%, which is basically very good news, a recession ensues. The basic intuition is that those news are even better than a permanent gain in productivity, it's a permanent increase in the speed of productivity growth and people feel they can afford to work and invest less than before, because even if we don't have that much capital or don't put in much hours, salaries and capital rental payments are going to be higher sooner than before and they can afford to eat more and work less.

To fix ideas, let's see what it means for productivity to grow at 2, 3 or 4 percent every year. If it grows at 2\%, it will take 35 years to double its size. If it grows at 3\% or 4\% it will only take only 23 or 17 years to double, respectively. In the same period that it takes to double its size by growing at 2\%, productivity would have almost tripled if growing at 3\% or it would be 4 times bigger if growing at 4\%. Those are significant changes induced by a rise of the long term growth. If wages and rental price of capital rise with productivity, these are potentially large changes in wealth, too.

Some researchers like rebelo and jaimovich focus their attention on the pure-income effect on labor supply and devise a type of utility function that make agents to less likely to work less just because future income now seems higher.The problem  to be addressed was oversensitive preferences for leisure. But I'm interested in different line of attack: changes in trend growth may occur, but may fail to act on them due to informational imperfections. Maybe the cannot tell for sure if they are facing a temporary or a permanent change in trend growth. Maybe even if they were sure the best approximation to what is happening is a permanent long term growth, the are unsure about possible deviations of this behavior that they cannot anticipate or formulate. The former deals with imperfect information and the second with methods of robust control. In any case, the permanent good news are treated with more caution (it can be temporary, it can evolve in unexpected ways) and as a result we don't see people working and investing less. In this line, the problem to be addressed is full information or excess of certainties.

In what follow, we will build, discuss and solve the simplest environment that can think of preferences, productivity and technology that will allow me to examine the consequences of permanent changes in trend growth under full information, imperfect information and unstructured model uncertainty. I will grant the not so gracious name of Toy Model to such environment and its setup is described in the next section.


## Further numerical examples on trend growth ##

Let's kkep the focus on growth rates of 2\% and 4\% and doubling the current level of productivity

### permanent change in tren growth from 2\% to 4\% ###

### transitory versus permanent ### 

### persistent versus permanent ###



